### ISSUE TITLE
Structure comment for Week 2 and Week 3

### ISSUE THREAD

**Issue by shivanivj** [atyre2/data-management#1]
Comment: The first two videos from Week 3 (Video on Data types and vectors and
Video with more Vectors and Factors) appear to match the material in the second and third readings from Week 2 (Introduction to R and Starting with data), respectively, and not the readings from Week 3.

**Comment by atyre2** [comment]
Thanks for putting in the lengths! I see what you mean, but I think it's OK. Those videos are going into greater depth than the readings, and the exercises for that week still draw heavily on those skills. Intro-01 reading / video list is already pretty big. 

git saved my bacon today -- I confused R-data-02 with R-intro-02 and started hacking and chopping, only to realize that I wasn't working on the right bit! Revert, and <phew>!
